#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChuyenDe")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUYENDE(CHUYENDE instance);
    partial void UpdateCHUYENDE(CHUYENDE instance);
    partial void DeleteCHUYENDE(CHUYENDE instance);
    partial void InsertGIAOVIEN(GIAOVIEN instance);
    partial void UpdateGIAOVIEN(GIAOVIEN instance);
    partial void DeleteGIAOVIEN(GIAOVIEN instance);
    partial void InsertGIAOVU(GIAOVU instance);
    partial void UpdateGIAOVU(GIAOVU instance);
    partial void DeleteGIAOVU(GIAOVU instance);
    partial void InsertHOCKY(HOCKY instance);
    partial void UpdateHOCKY(HOCKY instance);
    partial void DeleteHOCKY(HOCKY instance);
    partial void InsertLOPHOC(LOPHOC instance);
    partial void UpdateLOPHOC(LOPHOC instance);
    partial void DeleteLOPHOC(LOPHOC instance);
    partial void InsertNGANH(NGANH instance);
    partial void UpdateNGANH(NGANH instance);
    partial void DeleteNGANH(NGANH instance);
    partial void InsertNHOM(NHOM instance);
    partial void UpdateNHOM(NHOM instance);
    partial void DeleteNHOM(NHOM instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHONGTINMOCHUYENDE(THONGTINMOCHUYENDE instance);
    partial void UpdateTHONGTINMOCHUYENDE(THONGTINMOCHUYENDE instance);
    partial void DeleteTHONGTINMOCHUYENDE(THONGTINMOCHUYENDE instance);
    partial void InsertTHONGTINDANGKY(THONGTINDANGKY instance);
    partial void UpdateTHONGTINDANGKY(THONGTINDANGKY instance);
    partial void DeleteTHONGTINDANGKY(THONGTINDANGKY instance);
    partial void InsertTHANHVIEN(THANHVIEN instance);
    partial void UpdateTHANHVIEN(THANHVIEN instance);
    partial void DeleteTHANHVIEN(THANHVIEN instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::PROJECT.Properties.Settings.Default.QuanLyChuyenDeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUYENDE> CHUYENDEs
		{
			get
			{
				return this.GetTable<CHUYENDE>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this.GetTable<GIAOVIEN>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVU> GIAOVUs
		{
			get
			{
				return this.GetTable<GIAOVU>();
			}
		}
		
		public System.Data.Linq.Table<HOCKY> HOCKies
		{
			get
			{
				return this.GetTable<HOCKY>();
			}
		}
		
		public System.Data.Linq.Table<LOPHOC> LOPHOCs
		{
			get
			{
				return this.GetTable<LOPHOC>();
			}
		}
		
		public System.Data.Linq.Table<NGANH> NGANHs
		{
			get
			{
				return this.GetTable<NGANH>();
			}
		}
		
		public System.Data.Linq.Table<NHOM> NHOMs
		{
			get
			{
				return this.GetTable<NHOM>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINMOCHUYENDE> THONGTINMOCHUYENDEs
		{
			get
			{
				return this.GetTable<THONGTINMOCHUYENDE>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINDANGKY> THONGTINDANGKies
		{
			get
			{
				return this.GetTable<THONGTINDANGKY>();
			}
		}
		
		public System.Data.Linq.Table<THANHVIEN> THANHVIENs
		{
			get
			{
				return this.GetTable<THANHVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYENDE")]
	public partial class CHUYENDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChuyenDe;
		
		private string _TenChuyenDe;
		
		private System.Nullable<int> _SoSinhVienToiDa;
		
		private string _MaNganh;
		
		private EntitySet<GIAOVIEN> _GIAOVIENs;
		
		private EntitySet<THONGTINMOCHUYENDE> _THONGTINMOCHUYENDEs;
		
		private EntityRef<NGANH> _NGANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuyenDeChanging(string value);
    partial void OnMaChuyenDeChanged();
    partial void OnTenChuyenDeChanging(string value);
    partial void OnTenChuyenDeChanged();
    partial void OnSoSinhVienToiDaChanging(System.Nullable<int> value);
    partial void OnSoSinhVienToiDaChanged();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    #endregion
		
		public CHUYENDE()
		{
			this._GIAOVIENs = new EntitySet<GIAOVIEN>(new Action<GIAOVIEN>(this.attach_GIAOVIENs), new Action<GIAOVIEN>(this.detach_GIAOVIENs));
			this._THONGTINMOCHUYENDEs = new EntitySet<THONGTINMOCHUYENDE>(new Action<THONGTINMOCHUYENDE>(this.attach_THONGTINMOCHUYENDEs), new Action<THONGTINMOCHUYENDE>(this.detach_THONGTINMOCHUYENDEs));
			this._NGANH = default(EntityRef<NGANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenDe", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChuyenDe
		{
			get
			{
				return this._MaChuyenDe;
			}
			set
			{
				if ((this._MaChuyenDe != value))
				{
					this.OnMaChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenDe = value;
					this.SendPropertyChanged("MaChuyenDe");
					this.OnMaChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenDe", DbType="NVarChar(50)")]
		public string TenChuyenDe
		{
			get
			{
				return this._TenChuyenDe;
			}
			set
			{
				if ((this._TenChuyenDe != value))
				{
					this.OnTenChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._TenChuyenDe = value;
					this.SendPropertyChanged("TenChuyenDe");
					this.OnTenChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSinhVienToiDa", DbType="Int")]
		public System.Nullable<int> SoSinhVienToiDa
		{
			get
			{
				return this._SoSinhVienToiDa;
			}
			set
			{
				if ((this._SoSinhVienToiDa != value))
				{
					this.OnSoSinhVienToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoSinhVienToiDa = value;
					this.SendPropertyChanged("SoSinhVienToiDa");
					this.OnSoSinhVienToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="Char(10)")]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_GIAOVIEN", Storage="_GIAOVIENs", ThisKey="MaChuyenDe", OtherKey="MaChuyenDe")]
		public EntitySet<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this._GIAOVIENs;
			}
			set
			{
				this._GIAOVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_THONGTINMOCHUYENDE", Storage="_THONGTINMOCHUYENDEs", ThisKey="MaChuyenDe", OtherKey="MaChuyenDe")]
		public EntitySet<THONGTINMOCHUYENDE> THONGTINMOCHUYENDEs
		{
			get
			{
				return this._THONGTINMOCHUYENDEs;
			}
			set
			{
				this._THONGTINMOCHUYENDEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHUYENDE", Storage="_NGANH", ThisKey="MaNganh", OtherKey="MaNganh", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.CHUYENDEs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.CHUYENDEs.Add(this);
						this._MaNganh = value.MaNganh;
					}
					else
					{
						this._MaNganh = default(string);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENDE = this;
		}
		
		private void detach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENDE = null;
		}
		
		private void attach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENDE = this;
		}
		
		private void detach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENDE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVIEN")]
	public partial class GIAOVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoVien;
		
		private string _TenGiaoVien;
		
		private System.Nullable<bool> _Phai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _MaChuyenDe;
		
		private EntityRef<CHUYENDE> _CHUYENDE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoVienChanging(string value);
    partial void OnMaGiaoVienChanged();
    partial void OnTenGiaoVienChanging(string value);
    partial void OnTenGiaoVienChanged();
    partial void OnPhaiChanging(System.Nullable<bool> value);
    partial void OnPhaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaChuyenDeChanging(string value);
    partial void OnMaChuyenDeChanged();
    #endregion
		
		public GIAOVIEN()
		{
			this._CHUYENDE = default(EntityRef<CHUYENDE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoVien
		{
			get
			{
				return this._MaGiaoVien;
			}
			set
			{
				if ((this._MaGiaoVien != value))
				{
					this.OnMaGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVien = value;
					this.SendPropertyChanged("MaGiaoVien");
					this.OnMaGiaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiaoVien", DbType="NVarChar(50)")]
		public string TenGiaoVien
		{
			get
			{
				return this._TenGiaoVien;
			}
			set
			{
				if ((this._TenGiaoVien != value))
				{
					this.OnTenGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._TenGiaoVien = value;
					this.SendPropertyChanged("TenGiaoVien");
					this.OnTenGiaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phai", DbType="Bit")]
		public System.Nullable<bool> Phai
		{
			get
			{
				return this._Phai;
			}
			set
			{
				if ((this._Phai != value))
				{
					this.OnPhaiChanging(value);
					this.SendPropertyChanging();
					this._Phai = value;
					this.SendPropertyChanged("Phai");
					this.OnPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(231)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenDe", DbType="Char(10)")]
		public string MaChuyenDe
		{
			get
			{
				return this._MaChuyenDe;
			}
			set
			{
				if ((this._MaChuyenDe != value))
				{
					if (this._CHUYENDE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenDe = value;
					this.SendPropertyChanged("MaChuyenDe");
					this.OnMaChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_GIAOVIEN", Storage="_CHUYENDE", ThisKey="MaChuyenDe", OtherKey="MaChuyenDe", IsForeignKey=true)]
		public CHUYENDE CHUYENDE
		{
			get
			{
				return this._CHUYENDE.Entity;
			}
			set
			{
				CHUYENDE previousValue = this._CHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._CHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUYENDE.Entity = null;
						previousValue.GIAOVIENs.Remove(this);
					}
					this._CHUYENDE.Entity = value;
					if ((value != null))
					{
						value.GIAOVIENs.Add(this);
						this._MaChuyenDe = value.MaChuyenDe;
					}
					else
					{
						this._MaChuyenDe = default(string);
					}
					this.SendPropertyChanged("CHUYENDE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVU")]
	public partial class GIAOVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoVu;
		
		private string _TenGiaoVu;
		
		private System.Nullable<bool> _Phai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntitySet<THONGTINMOCHUYENDE> _THONGTINMOCHUYENDEs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoVuChanging(string value);
    partial void OnMaGiaoVuChanged();
    partial void OnTenGiaoVuChanging(string value);
    partial void OnTenGiaoVuChanged();
    partial void OnPhaiChanging(System.Nullable<bool> value);
    partial void OnPhaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public GIAOVU()
		{
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._THONGTINMOCHUYENDEs = new EntitySet<THONGTINMOCHUYENDE>(new Action<THONGTINMOCHUYENDE>(this.attach_THONGTINMOCHUYENDEs), new Action<THONGTINMOCHUYENDE>(this.detach_THONGTINMOCHUYENDEs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVu", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoVu
		{
			get
			{
				return this._MaGiaoVu;
			}
			set
			{
				if ((this._MaGiaoVu != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaoVuChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVu = value;
					this.SendPropertyChanged("MaGiaoVu");
					this.OnMaGiaoVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiaoVu", DbType="NVarChar(50)")]
		public string TenGiaoVu
		{
			get
			{
				return this._TenGiaoVu;
			}
			set
			{
				if ((this._TenGiaoVu != value))
				{
					this.OnTenGiaoVuChanging(value);
					this.SendPropertyChanging();
					this._TenGiaoVu = value;
					this.SendPropertyChanged("TenGiaoVu");
					this.OnTenGiaoVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phai", DbType="Bit")]
		public System.Nullable<bool> Phai
		{
			get
			{
				return this._Phai;
			}
			set
			{
				if ((this._Phai != value))
				{
					this.OnPhaiChanging(value);
					this.SendPropertyChanging();
					this._Phai = value;
					this.SendPropertyChanged("Phai");
					this.OnPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(231)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MaGiaoVu", OtherKey="MaGiaoVuTao")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_THONGTINMOCHUYENDE", Storage="_THONGTINMOCHUYENDEs", ThisKey="MaGiaoVu", OtherKey="MaGiaoVu")]
		public EntitySet<THONGTINMOCHUYENDE> THONGTINMOCHUYENDEs
		{
			get
			{
				return this._THONGTINMOCHUYENDEs;
			}
			set
			{
				this._THONGTINMOCHUYENDEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVU", Storage="_TAIKHOAN", ThisKey="MaGiaoVu", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.GIAOVU = null;
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.GIAOVU = this;
						this._MaGiaoVu = value.MaTaiKhoan;
					}
					else
					{
						this._MaGiaoVu = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU1 = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU1 = null;
		}
		
		private void attach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU = this;
		}
		
		private void detach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCKY")]
	public partial class HOCKY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HocKy1;
		
		private string _NienHoc;
		
		private System.Nullable<System.DateTime> _NgayBatDau;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private EntitySet<THONGTINMOCHUYENDE> _THONGTINMOCHUYENDEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHocKy1Changing(int value);
    partial void OnHocKy1Changed();
    partial void OnNienHocChanging(string value);
    partial void OnNienHocChanged();
    partial void OnNgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucChanged();
    #endregion
		
		public HOCKY()
		{
			this._THONGTINMOCHUYENDEs = new EntitySet<THONGTINMOCHUYENDE>(new Action<THONGTINMOCHUYENDE>(this.attach_THONGTINMOCHUYENDEs), new Action<THONGTINMOCHUYENDE>(this.detach_THONGTINMOCHUYENDEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HocKy", Storage="_HocKy1", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HocKy1
		{
			get
			{
				return this._HocKy1;
			}
			set
			{
				if ((this._HocKy1 != value))
				{
					this.OnHocKy1Changing(value);
					this.SendPropertyChanging();
					this._HocKy1 = value;
					this.SendPropertyChanged("HocKy1");
					this.OnHocKy1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienHoc", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NienHoc
		{
			get
			{
				return this._NienHoc;
			}
			set
			{
				if ((this._NienHoc != value))
				{
					this.OnNienHocChanging(value);
					this.SendPropertyChanging();
					this._NienHoc = value;
					this.SendPropertyChanged("NienHoc");
					this.OnNienHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCKY_THONGTINMOCHUYENDE", Storage="_THONGTINMOCHUYENDEs", ThisKey="HocKy1,NienHoc", OtherKey="HocKy,NienHoc")]
		public EntitySet<THONGTINMOCHUYENDE> THONGTINMOCHUYENDEs
		{
			get
			{
				return this._THONGTINMOCHUYENDEs;
			}
			set
			{
				this._THONGTINMOCHUYENDEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.HOCKY1 = this;
		}
		
		private void detach_THONGTINMOCHUYENDEs(THONGTINMOCHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.HOCKY1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOPHOC")]
	public partial class LOPHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private EntitySet<THONGTINDANGKY> _THONGTINDANGKies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    #endregion
		
		public LOPHOC()
		{
			this._THONGTINDANGKies = new EntitySet<THONGTINDANGKY>(new Action<THONGTINDANGKY>(this.attach_THONGTINDANGKies), new Action<THONGTINDANGKY>(this.detach_THONGTINDANGKies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPHOC_THONGTINDANGKY", Storage="_THONGTINDANGKies", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<THONGTINDANGKY> THONGTINDANGKies
		{
			get
			{
				return this._THONGTINDANGKies;
			}
			set
			{
				this._THONGTINDANGKies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.LOPHOC = this;
		}
		
		private void detach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.LOPHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGANH")]
	public partial class NGANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNganh;
		
		private string _TenNganh;
		
		private System.Nullable<int> _SoSinhVienTheoHoc;
		
		private System.Nullable<int> _SoChuyenDeToiDa;
		
		private EntitySet<CHUYENDE> _CHUYENDEs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    partial void OnTenNganhChanging(string value);
    partial void OnTenNganhChanged();
    partial void OnSoSinhVienTheoHocChanging(System.Nullable<int> value);
    partial void OnSoSinhVienTheoHocChanged();
    partial void OnSoChuyenDeToiDaChanging(System.Nullable<int> value);
    partial void OnSoChuyenDeToiDaChanged();
    #endregion
		
		public NGANH()
		{
			this._CHUYENDEs = new EntitySet<CHUYENDE>(new Action<CHUYENDE>(this.attach_CHUYENDEs), new Action<CHUYENDE>(this.detach_CHUYENDEs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(50)")]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this.OnTenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenNganh = value;
					this.SendPropertyChanged("TenNganh");
					this.OnTenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSinhVienTheoHoc", DbType="Int")]
		public System.Nullable<int> SoSinhVienTheoHoc
		{
			get
			{
				return this._SoSinhVienTheoHoc;
			}
			set
			{
				if ((this._SoSinhVienTheoHoc != value))
				{
					this.OnSoSinhVienTheoHocChanging(value);
					this.SendPropertyChanging();
					this._SoSinhVienTheoHoc = value;
					this.SendPropertyChanged("SoSinhVienTheoHoc");
					this.OnSoSinhVienTheoHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChuyenDeToiDa", DbType="Int")]
		public System.Nullable<int> SoChuyenDeToiDa
		{
			get
			{
				return this._SoChuyenDeToiDa;
			}
			set
			{
				if ((this._SoChuyenDeToiDa != value))
				{
					this.OnSoChuyenDeToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoChuyenDeToiDa = value;
					this.SendPropertyChanged("SoChuyenDeToiDa");
					this.OnSoChuyenDeToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHUYENDE", Storage="_CHUYENDEs", ThisKey="MaNganh", OtherKey="MaNganh")]
		public EntitySet<CHUYENDE> CHUYENDEs
		{
			get
			{
				return this._CHUYENDEs;
			}
			set
			{
				this._CHUYENDEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_SINHVIEN", Storage="_SINHVIENs", ThisKey="MaNganh", OtherKey="MaNganh")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUYENDEs(CHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_CHUYENDEs(CHUYENDE entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOM")]
	public partial class NHOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntitySet<THANHVIEN> _THANHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public NHOM()
		{
			this._THANHVIENs = new EntitySet<THANHVIEN>(new Action<THANHVIEN>(this.attach_THANHVIENs), new Action<THANHVIEN>(this.detach_THANHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(30)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_THANHVIEN", Storage="_THANHVIENs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<THANHVIEN> THANHVIENs
		{
			get
			{
				return this._THANHVIENs;
			}
			set
			{
				this._THANHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANHVIENs(THANHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOM = this;
		}
		
		private void detach_THANHVIENs(THANHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSinhVien;
		
		private string _TenSinhVien;
		
		private System.Nullable<bool> _Phai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _MaNganh;
		
		private EntitySet<THONGTINDANGKY> _THONGTINDANGKies;
		
		private EntityRef<NGANH> _NGANH;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSinhVienChanging(string value);
    partial void OnMaSinhVienChanged();
    partial void OnTenSinhVienChanging(string value);
    partial void OnTenSinhVienChanged();
    partial void OnPhaiChanging(System.Nullable<bool> value);
    partial void OnPhaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._THONGTINDANGKies = new EntitySet<THONGTINDANGKY>(new Action<THONGTINDANGKY>(this.attach_THONGTINDANGKies), new Action<THONGTINDANGKY>(this.detach_THONGTINDANGKies));
			this._NGANH = default(EntityRef<NGANH>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSinhVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSinhVien
		{
			get
			{
				return this._MaSinhVien;
			}
			set
			{
				if ((this._MaSinhVien != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._MaSinhVien = value;
					this.SendPropertyChanged("MaSinhVien");
					this.OnMaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSinhVien", DbType="NVarChar(50)")]
		public string TenSinhVien
		{
			get
			{
				return this._TenSinhVien;
			}
			set
			{
				if ((this._TenSinhVien != value))
				{
					this.OnTenSinhVienChanging(value);
					this.SendPropertyChanging();
					this._TenSinhVien = value;
					this.SendPropertyChanged("TenSinhVien");
					this.OnTenSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phai", DbType="Bit")]
		public System.Nullable<bool> Phai
		{
			get
			{
				return this._Phai;
			}
			set
			{
				if ((this._Phai != value))
				{
					this.OnPhaiChanging(value);
					this.SendPropertyChanging();
					this._Phai = value;
					this.SendPropertyChanged("Phai");
					this.OnPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(231)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="Char(10)")]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_THONGTINDANGKY", Storage="_THONGTINDANGKies", ThisKey="MaSinhVien", OtherKey="MaSinhVien")]
		public EntitySet<THONGTINDANGKY> THONGTINDANGKies
		{
			get
			{
				return this._THONGTINDANGKies;
			}
			set
			{
				this._THONGTINDANGKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_SINHVIEN", Storage="_NGANH", ThisKey="MaNganh", OtherKey="MaNganh", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MaNganh = value.MaNganh;
					}
					else
					{
						this._MaNganh = default(string);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_SINHVIEN", Storage="_TAIKHOAN", ThisKey="MaSinhVien", OtherKey="MaTaiKhoan", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.SINHVIEN = null;
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.SINHVIEN = this;
						this._MaSinhVien = value.MaTaiKhoan;
					}
					else
					{
						this._MaSinhVien = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = this;
		}
		
		private void detach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiKhoan;
		
		private string _MatKhau;
		
		private string _LoaiTaiKhoan;
		
		private string _MaGiaoVuTao;
		
		private EntityRef<GIAOVU> _GIAOVU;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
		private EntityRef<GIAOVU> _GIAOVU1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnLoaiTaiKhoanChanging(string value);
    partial void OnLoaiTaiKhoanChanged();
    partial void OnMaGiaoVuTaoChanging(string value);
    partial void OnMaGiaoVuTaoChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._GIAOVU = default(EntityRef<GIAOVU>);
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			this._GIAOVU1 = default(EntityRef<GIAOVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTaiKhoan", DbType="Char(5)")]
		public string LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan;
			}
			set
			{
				if ((this._LoaiTaiKhoan != value))
				{
					this.OnLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._LoaiTaiKhoan = value;
					this.SendPropertyChanged("LoaiTaiKhoan");
					this.OnLoaiTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVuTao", DbType="Char(10)")]
		public string MaGiaoVuTao
		{
			get
			{
				return this._MaGiaoVuTao;
			}
			set
			{
				if ((this._MaGiaoVuTao != value))
				{
					if (this._GIAOVU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaoVuTaoChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVuTao = value;
					this.SendPropertyChanged("MaGiaoVuTao");
					this.OnMaGiaoVuTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_GIAOVU", Storage="_GIAOVU", ThisKey="MaTaiKhoan", OtherKey="MaGiaoVu", IsUnique=true, IsForeignKey=false)]
		public GIAOVU GIAOVU
		{
			get
			{
				return this._GIAOVU.Entity;
			}
			set
			{
				GIAOVU previousValue = this._GIAOVU.Entity;
				if (((previousValue != value) 
							|| (this._GIAOVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAOVU.Entity = null;
						previousValue.TAIKHOAN = null;
					}
					this._GIAOVU.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN = this;
					}
					this.SendPropertyChanged("GIAOVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_SINHVIEN", Storage="_SINHVIEN", ThisKey="MaTaiKhoan", OtherKey="MaSinhVien", IsUnique=true, IsForeignKey=false)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.TAIKHOAN = null;
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN = this;
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_TAIKHOAN", Storage="_GIAOVU1", ThisKey="MaGiaoVuTao", OtherKey="MaGiaoVu", IsForeignKey=true)]
		public GIAOVU GIAOVU1
		{
			get
			{
				return this._GIAOVU1.Entity;
			}
			set
			{
				GIAOVU previousValue = this._GIAOVU1.Entity;
				if (((previousValue != value) 
							|| (this._GIAOVU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAOVU1.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._GIAOVU1.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MaGiaoVuTao = value.MaGiaoVu;
					}
					else
					{
						this._MaGiaoVuTao = default(string);
					}
					this.SendPropertyChanged("GIAOVU1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINMOCHUYENDE")]
	public partial class THONGTINMOCHUYENDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThongTinMoChuyenDe;
		
		private System.Nullable<int> _HocKy;
		
		private string _NienHoc;
		
		private string _MaGiaoVu;
		
		private string _MaChuyenDe;
		
		private EntitySet<THONGTINDANGKY> _THONGTINDANGKies;
		
		private EntityRef<CHUYENDE> _CHUYENDE;
		
		private EntityRef<GIAOVU> _GIAOVU;
		
		private EntityRef<HOCKY> _HOCKY1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThongTinMoChuyenDeChanging(string value);
    partial void OnMaThongTinMoChuyenDeChanged();
    partial void OnHocKyChanging(System.Nullable<int> value);
    partial void OnHocKyChanged();
    partial void OnNienHocChanging(string value);
    partial void OnNienHocChanged();
    partial void OnMaGiaoVuChanging(string value);
    partial void OnMaGiaoVuChanged();
    partial void OnMaChuyenDeChanging(string value);
    partial void OnMaChuyenDeChanged();
    #endregion
		
		public THONGTINMOCHUYENDE()
		{
			this._THONGTINDANGKies = new EntitySet<THONGTINDANGKY>(new Action<THONGTINDANGKY>(this.attach_THONGTINDANGKies), new Action<THONGTINDANGKY>(this.detach_THONGTINDANGKies));
			this._CHUYENDE = default(EntityRef<CHUYENDE>);
			this._GIAOVU = default(EntityRef<GIAOVU>);
			this._HOCKY1 = default(EntityRef<HOCKY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThongTinMoChuyenDe", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThongTinMoChuyenDe
		{
			get
			{
				return this._MaThongTinMoChuyenDe;
			}
			set
			{
				if ((this._MaThongTinMoChuyenDe != value))
				{
					this.OnMaThongTinMoChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._MaThongTinMoChuyenDe = value;
					this.SendPropertyChanged("MaThongTinMoChuyenDe");
					this.OnMaThongTinMoChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					if (this._HOCKY1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHocKyChanging(value);
					this.SendPropertyChanging();
					this._HocKy = value;
					this.SendPropertyChanged("HocKy");
					this.OnHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienHoc", DbType="Char(20)")]
		public string NienHoc
		{
			get
			{
				return this._NienHoc;
			}
			set
			{
				if ((this._NienHoc != value))
				{
					if (this._HOCKY1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNienHocChanging(value);
					this.SendPropertyChanging();
					this._NienHoc = value;
					this.SendPropertyChanged("NienHoc");
					this.OnNienHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVu", DbType="Char(10)")]
		public string MaGiaoVu
		{
			get
			{
				return this._MaGiaoVu;
			}
			set
			{
				if ((this._MaGiaoVu != value))
				{
					if (this._GIAOVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaoVuChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVu = value;
					this.SendPropertyChanged("MaGiaoVu");
					this.OnMaGiaoVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenDe", DbType="Char(10)")]
		public string MaChuyenDe
		{
			get
			{
				return this._MaChuyenDe;
			}
			set
			{
				if ((this._MaChuyenDe != value))
				{
					if (this._CHUYENDE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenDe = value;
					this.SendPropertyChanged("MaChuyenDe");
					this.OnMaChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINMOCHUYENDE_THONGTINDANGKY", Storage="_THONGTINDANGKies", ThisKey="MaThongTinMoChuyenDe", OtherKey="MaThongTinMoChuyenDe")]
		public EntitySet<THONGTINDANGKY> THONGTINDANGKies
		{
			get
			{
				return this._THONGTINDANGKies;
			}
			set
			{
				this._THONGTINDANGKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENDE_THONGTINMOCHUYENDE", Storage="_CHUYENDE", ThisKey="MaChuyenDe", OtherKey="MaChuyenDe", IsForeignKey=true)]
		public CHUYENDE CHUYENDE
		{
			get
			{
				return this._CHUYENDE.Entity;
			}
			set
			{
				CHUYENDE previousValue = this._CHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._CHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUYENDE.Entity = null;
						previousValue.THONGTINMOCHUYENDEs.Remove(this);
					}
					this._CHUYENDE.Entity = value;
					if ((value != null))
					{
						value.THONGTINMOCHUYENDEs.Add(this);
						this._MaChuyenDe = value.MaChuyenDe;
					}
					else
					{
						this._MaChuyenDe = default(string);
					}
					this.SendPropertyChanged("CHUYENDE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVU_THONGTINMOCHUYENDE", Storage="_GIAOVU", ThisKey="MaGiaoVu", OtherKey="MaGiaoVu", IsForeignKey=true)]
		public GIAOVU GIAOVU
		{
			get
			{
				return this._GIAOVU.Entity;
			}
			set
			{
				GIAOVU previousValue = this._GIAOVU.Entity;
				if (((previousValue != value) 
							|| (this._GIAOVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAOVU.Entity = null;
						previousValue.THONGTINMOCHUYENDEs.Remove(this);
					}
					this._GIAOVU.Entity = value;
					if ((value != null))
					{
						value.THONGTINMOCHUYENDEs.Add(this);
						this._MaGiaoVu = value.MaGiaoVu;
					}
					else
					{
						this._MaGiaoVu = default(string);
					}
					this.SendPropertyChanged("GIAOVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCKY_THONGTINMOCHUYENDE", Storage="_HOCKY1", ThisKey="HocKy,NienHoc", OtherKey="HocKy1,NienHoc", IsForeignKey=true)]
		public HOCKY HOCKY1
		{
			get
			{
				return this._HOCKY1.Entity;
			}
			set
			{
				HOCKY previousValue = this._HOCKY1.Entity;
				if (((previousValue != value) 
							|| (this._HOCKY1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCKY1.Entity = null;
						previousValue.THONGTINMOCHUYENDEs.Remove(this);
					}
					this._HOCKY1.Entity = value;
					if ((value != null))
					{
						value.THONGTINMOCHUYENDEs.Add(this);
						this._HocKy = value.HocKy1;
						this._NienHoc = value.NienHoc;
					}
					else
					{
						this._HocKy = default(Nullable<int>);
						this._NienHoc = default(string);
					}
					this.SendPropertyChanged("HOCKY1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINMOCHUYENDE = this;
		}
		
		private void detach_THONGTINDANGKies(THONGTINDANGKY entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINMOCHUYENDE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINDANGKY")]
	public partial class THONGTINDANGKY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDangKy;
		
		private string _MaSinhVien;
		
		private string _MaThongTinMoChuyenDe;
		
		private string _MaLop;
		
		private EntitySet<THANHVIEN> _THANHVIENs;
		
		private EntityRef<LOPHOC> _LOPHOC;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
		private EntityRef<THONGTINMOCHUYENDE> _THONGTINMOCHUYENDE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDangKyChanging(string value);
    partial void OnMaDangKyChanged();
    partial void OnMaSinhVienChanging(string value);
    partial void OnMaSinhVienChanged();
    partial void OnMaThongTinMoChuyenDeChanging(string value);
    partial void OnMaThongTinMoChuyenDeChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    #endregion
		
		public THONGTINDANGKY()
		{
			this._THANHVIENs = new EntitySet<THANHVIEN>(new Action<THANHVIEN>(this.attach_THANHVIENs), new Action<THANHVIEN>(this.detach_THANHVIENs));
			this._LOPHOC = default(EntityRef<LOPHOC>);
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			this._THONGTINMOCHUYENDE = default(EntityRef<THONGTINMOCHUYENDE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKy", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDangKy
		{
			get
			{
				return this._MaDangKy;
			}
			set
			{
				if ((this._MaDangKy != value))
				{
					this.OnMaDangKyChanging(value);
					this.SendPropertyChanging();
					this._MaDangKy = value;
					this.SendPropertyChanged("MaDangKy");
					this.OnMaDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSinhVien", DbType="Char(10)")]
		public string MaSinhVien
		{
			get
			{
				return this._MaSinhVien;
			}
			set
			{
				if ((this._MaSinhVien != value))
				{
					if (this._SINHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._MaSinhVien = value;
					this.SendPropertyChanged("MaSinhVien");
					this.OnMaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThongTinMoChuyenDe", DbType="Char(10)")]
		public string MaThongTinMoChuyenDe
		{
			get
			{
				return this._MaThongTinMoChuyenDe;
			}
			set
			{
				if ((this._MaThongTinMoChuyenDe != value))
				{
					if (this._THONGTINMOCHUYENDE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThongTinMoChuyenDeChanging(value);
					this.SendPropertyChanging();
					this._MaThongTinMoChuyenDe = value;
					this.SendPropertyChanged("MaThongTinMoChuyenDe");
					this.OnMaThongTinMoChuyenDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._LOPHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINDANGKY_THANHVIEN", Storage="_THANHVIENs", ThisKey="MaDangKy", OtherKey="MaDangKy")]
		public EntitySet<THANHVIEN> THANHVIENs
		{
			get
			{
				return this._THANHVIENs;
			}
			set
			{
				this._THANHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOPHOC_THONGTINDANGKY", Storage="_LOPHOC", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public LOPHOC LOPHOC
		{
			get
			{
				return this._LOPHOC.Entity;
			}
			set
			{
				LOPHOC previousValue = this._LOPHOC.Entity;
				if (((previousValue != value) 
							|| (this._LOPHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOPHOC.Entity = null;
						previousValue.THONGTINDANGKies.Remove(this);
					}
					this._LOPHOC.Entity = value;
					if ((value != null))
					{
						value.THONGTINDANGKies.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("LOPHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_THONGTINDANGKY", Storage="_SINHVIEN", ThisKey="MaSinhVien", OtherKey="MaSinhVien", IsForeignKey=true)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.THONGTINDANGKies.Remove(this);
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.THONGTINDANGKies.Add(this);
						this._MaSinhVien = value.MaSinhVien;
					}
					else
					{
						this._MaSinhVien = default(string);
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINMOCHUYENDE_THONGTINDANGKY", Storage="_THONGTINMOCHUYENDE", ThisKey="MaThongTinMoChuyenDe", OtherKey="MaThongTinMoChuyenDe", IsForeignKey=true)]
		public THONGTINMOCHUYENDE THONGTINMOCHUYENDE
		{
			get
			{
				return this._THONGTINMOCHUYENDE.Entity;
			}
			set
			{
				THONGTINMOCHUYENDE previousValue = this._THONGTINMOCHUYENDE.Entity;
				if (((previousValue != value) 
							|| (this._THONGTINMOCHUYENDE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONGTINMOCHUYENDE.Entity = null;
						previousValue.THONGTINDANGKies.Remove(this);
					}
					this._THONGTINMOCHUYENDE.Entity = value;
					if ((value != null))
					{
						value.THONGTINDANGKies.Add(this);
						this._MaThongTinMoChuyenDe = value.MaThongTinMoChuyenDe;
					}
					else
					{
						this._MaThongTinMoChuyenDe = default(string);
					}
					this.SendPropertyChanged("THONGTINMOCHUYENDE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANHVIENs(THANHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINDANGKY = this;
		}
		
		private void detach_THANHVIENs(THANHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINDANGKY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHVIEN")]
	public partial class THANHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDangKy;
		
		private string _MaNhom;
		
		private string _VaiTro;
		
		private EntityRef<NHOM> _NHOM;
		
		private EntityRef<THONGTINDANGKY> _THONGTINDANGKY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDangKyChanging(string value);
    partial void OnMaDangKyChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnVaiTroChanging(string value);
    partial void OnVaiTroChanged();
    #endregion
		
		public THANHVIEN()
		{
			this._NHOM = default(EntityRef<NHOM>);
			this._THONGTINDANGKY = default(EntityRef<THONGTINDANGKY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKy", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDangKy
		{
			get
			{
				return this._MaDangKy;
			}
			set
			{
				if ((this._MaDangKy != value))
				{
					if (this._THONGTINDANGKY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDangKyChanging(value);
					this.SendPropertyChanging();
					this._MaDangKy = value;
					this.SendPropertyChanged("MaDangKy");
					this.OnMaDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NHOM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="NChar(20)")]
		public string VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_THANHVIEN", Storage="_NHOM", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NHOM NHOM
		{
			get
			{
				return this._NHOM.Entity;
			}
			set
			{
				NHOM previousValue = this._NHOM.Entity;
				if (((previousValue != value) 
							|| (this._NHOM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOM.Entity = null;
						previousValue.THANHVIENs.Remove(this);
					}
					this._NHOM.Entity = value;
					if ((value != null))
					{
						value.THANHVIENs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NHOM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINDANGKY_THANHVIEN", Storage="_THONGTINDANGKY", ThisKey="MaDangKy", OtherKey="MaDangKy", IsForeignKey=true)]
		public THONGTINDANGKY THONGTINDANGKY
		{
			get
			{
				return this._THONGTINDANGKY.Entity;
			}
			set
			{
				THONGTINDANGKY previousValue = this._THONGTINDANGKY.Entity;
				if (((previousValue != value) 
							|| (this._THONGTINDANGKY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONGTINDANGKY.Entity = null;
						previousValue.THANHVIENs.Remove(this);
					}
					this._THONGTINDANGKY.Entity = value;
					if ((value != null))
					{
						value.THANHVIENs.Add(this);
						this._MaDangKy = value.MaDangKy;
					}
					else
					{
						this._MaDangKy = default(string);
					}
					this.SendPropertyChanged("THONGTINDANGKY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
